---
title: "Ecosystem Service: Water Use, a Provisioning Service"
format:
  docx:
    reference-doc: word_template_noindent.docx
    toc: false
    toc-depth: 3
    number-sections: false
    colorlinks: true
bibliography: ../../../2_Water_General.bib
# csl: science-without-titles.csl
execute:
  cache: false
  echo: false
  message: false
  error: false
---

```{r}
#| include: false
library(here)
i_am("WaterUse/Gitcontrolled/Writing/Appendix_WaterUse.qmd")
```                                                             

# Introduction {-}

Nature’s provisioning service for freshwater is a fundamental ecosystem service for sustaining both human well-being and the functioning of ecological systems. Freshwater enables essential services across agricultural, industrial, and domestic sectors. As global water demand increases due to population growth, economic development, and climate change, the role of nature's freshwater provisioning service becomes increasingly important [@Brauman.etal2007; @Vorosmarty.etal2000].

In agriculture, freshwater provisioning enables irrigation, which stabilizes and enhances crop yields, especially in arid and semi-arid regions where precipitation during the growing season is insufficient to meet crop water needs. For example, in the U.S. western part of the Great Plains region, average precipitation during the critical growing season (May to August) ranges well below the typically required for high-yielding corn or wheat without supplemental water. Despite this climatic limitation, irrigation—primarily drawing from the Ogallala aquifer has transformed the region into one of the most productive agricultural zones in the world. Irrigated agriculture currently accounts for more than 70 percent of global feshwater withdrawals, and it contributes approximately 40% of the world's food production [@FAO2020]

In the industrial sector, water is a key input for manufacturing, energy production, and cooling processes. Industries such as food processing, paper manufacturing, chemical production, petroleum refining, and metal fabrication rely heavily on water to maintain operational efficiency and product quality [@USGS2018]. 

In the domestic sector, freshwater provisioning is an essential service that supports people's daily needs for drinking water, and other basic activities such as hygine and sanitation [@UN2023]. In terms of drinking water. Although domestic water use accounts for only about 12 percent of freshwater withdrawals grobally, which is the lowest among the three sectores, water demand from the domestic sector has been significantly increasing relative to the other two sectores partly due to growing global population and urbanization trends [@UN2024]. Under such circumstances, the role of nature's freshwater provisioning service becomes increasingly important for ensuring access to freshwater. 

In this section, we quantify the contribution of nature’s freshwater provisioning service to human well-being by calculating the Global Ecosystem Product (GEP) of water use across irrigation, industrial, and domestic sectors. By assigning value to the physical water flows delivered by ecosystems, we aim to highlight the economic significance of this often-overlooked ecosystem service.

## Data and Methodology {-}

To derive the GEP of water use, we use market price approach. This approach is used in the previous studies deriving the GEP of water use (e.g., @Deng.etal2025; @Geng.Liang2021; **@Huang.etal2022**, ; @Ouyang.etal2020; @Pacetti.etal2024; @Zhang.etal2024.) With this approach, the GEP of water use is calculated by multiplying the physical flow of water used by the market price of water for each sector, and them summing the values across all sectors. The formula for calculating the GEP of water use is as follows:

$$
\text{GEP of Water Use} = \sum_{i} (P_i \times Q_i)
$$
, where $P_i$ is the market price of water for sector $i$ and $Q_i$ is the physical flow of water used in sector $i$. The summation is done across all sectors, including irrigation, industry, and domestic use.

The data on the physical flow of water used in each sector ($Q_i$) are sourced from the FAO AQUASTAT database [@FAO2025], which provides comprehensive data on water use across different sectors globally. For the physical flow of water used in each sector, we use country-level data on water withdrawals (in $m^3$) for irrigation, industry, and domestic use. The market price of water is not directly available in the AQUASTAT database.  Indeed, it is almost impossible to obtain the market price of water for each sector globally, as water is rarely traded in open markets. The prices are typically set through administrative or subsidized mechanisms rather than market forces. As a result, water pricing varies widely by country and region, reflecting local governance structures, cost-recovery policies, and levels of infrastructure investment, rather than marginal economic value. Due to this limitation, we use the value of water use efficiency (WUE, in $\$/m^3$) for each sector and country as a proxy for the market price of water. WUE is defined as the economic value generated per unit of water used for each sector [@FAO2018]. For example, WUE for irrigation is calculated as the value of agricultural output per unit of water used for irrigation, which is shown in the following formula:

$$
\text{WUE}_{\text{Irrigation}} = \frac{\text{Gross value added by irrigated agriculture}}{\text{Volume of water used for agricultural sector}}
$$

WUE is converted to a common unit of $\$/m^3$ and deflated to the baseline year 2015. The use of WUE as a proxy for the market price of water may overstate the the actual market price of water, because WUE reflects the total value of output per unit of water, which includes contributions from other inputs such as capital and labor rather than just the marginal value of water itself. In this light, the derived GEP of water use should be interpreted as the upper bound of the value, rather. However, it provides a conosistent and globally available indicator of the average economic return to water use. Furthermore, it is defensible in a global ecosystem service accounting framework. This is because water use efficiency is calculated from observable and publicly available data, and thus offers a transparent and globally comparable measure of how much economic value is generated per unit of water used in each sector.


## Limitations and Future Directions {-}

\newpage 

## References {-}
